config/routes.rb
ImgurClone::Application.routes.draw do
  root :to => 'sessions#new'
  
  get "auth/facebook/callback" => "sessions#create"
  
  resources :home, only: [:index]

  resources :users, only: [:new, :create] do
    resources :photos, only: [:create]
    
    resources :regions, only: [:index, :new, :create]

    member do
      get "favorites"
      get "uploaded_images"
    end
  end

  resource :session, only: [:new, :create, :destroy]

  resources :photos, only: [:index, :show, :update, :destroy] do
    resources :comments,  only: [:create, :index] 
    resources :user_votes, only: [:index]
    resources :favorites, only: [:create]

    member do
      post "upvote"
      post "downvote"
      post "cancelvote"
    end
  end

  resources :regions, only: [:show, :edit, :update, :destroy]
  resources :comments,  only: [:destroy]
  resources :favorites, only: [:destroy]

  resource :password_reset, only: [:new, :create, :edit, :update]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :commenter_id, :parent_comment_id, :photo_id, :body

  validates :commenter_id, :body, :photo_id, presence: true

  belongs_to(
    :commenter,
    class_name: "User",
    foreign_key: :commenter_id,
    primary_key: :id
  )

  belongs_to(
    :photo,
    class_name: "Photo",
    foreign_key: :photo_id,
    primary_key: :id
  )

  belongs_to(
    :parent_comment,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id
  )

  has_many(
    :child_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id
  )



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :json
  
  def index
    @photo = Photo.find(params[:photo_id])
    @comments = @photo.comments
    
    respond_with @comments
  end

  def create
    @comment = Comment.new(params[:comment])
    @comment.commenter_id = self.current_user.id
    # @comment.update_attributes(commenter_id: self.current_user.id)

    if @comment.save
      respond_with @comment
    else
      flash[:errors] = @comment.errors.full_messages
      respond_with @comment
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    
    respond_with @comment
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_form.html.erb
<form action="<%= photo_comments_url(params[:photo_id])%>" method="post">

  <input type="hidden"
         name="authenticity_token"
        value="<%= form_authenticity_token %>">

  <% if params[:parent_comment_id] %>
     <input type="hidden"
            name="comment[parent_comment_id]"
           value="<%= params[:parent_comment_id] %>">
  <% end %>

  <input type="text" name="comment[body]" placeholder="Submit a Comment">

  <input type="submit", value="Save">

</form>

app/views/comments/new.html.erb
<%= render "comments/comment_form", photo: @photo%>