config/routes.rb
ImgurClone::Application.routes.draw do
  root :to => 'sessions#new'
  
  get "auth/facebook/callback" => "sessions#create"
  
  resources :home, only: [:index]

  resources :users, only: [:new, :create] do
    resources :photos, only: [:create]
    
    resources :regions, only: [:index, :new, :create]

    member do
      get "favorites"
      get "uploaded_images"
    end
  end

  resource :session, only: [:new, :create, :destroy]

  resources :photos, only: [:index, :show, :update, :destroy] do
    resources :comments,  only: [:create, :index] 
    resources :user_votes, only: [:index]
    resources :favorites, only: [:create]

    member do
      post "upvote"
      post "downvote"
      post "cancelvote"
    end
  end

  resources :regions, only: [:show, :edit, :update, :destroy]
  resources :comments,  only: [:destroy]
  resources :favorites, only: [:destroy]

  resource :password_reset, only: [:new, :create, :edit, :update]

end

app/models/photo.rb
require 'addressable/uri'
require 'nokogiri'

class Photo < ActiveRecord::Base
  attr_accessible :submitter_id, :title, :description, :latitude, :longitude, :image 

  validates :submitter_id, :title, :latitude, :longitude, presence: true
  validates :image, attachment_presence: true
  
  before_validation :check_title, on: :create

  belongs_to(
    :submitter,
    class_name: "User",
    foreign_key: :submitter_id,
    primary_key: :id
  )

  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :photo_id,
    primary_key: :id
  )

  has_many(
    :uservotes,
    class_name: "UserVote",
    foreign_key: :photo_id,
    primary_key: :id
  )

  has_many(
    :favorites,
    class_name: "Favorite",
    foreign_key: :photo_id,
    primary_key: :id
  )

  has_many(
    :favoring_users, through: :favorites, source: :user
  )

  has_attached_file :image
  
  # def initialize(tempfile, attribute={})
  #   super(attribute)
  #   check_for_geotag(tempfile)
  # end

  def check_for_geotag(tempfile)
    imgfile = EXIFR::JPEG.new(tempfile)
    return if imgfile.nil?
    self.latitude = imgfile.gps.latitude
    self.longitude = imgfile.gps.longitude
  end
  
  def check_title
    self.title = "Untitled" if self.title.nil?
  end

  def comments_by_parent_id
    comments_by_parent = Hash.new { |hash, key| hash[key] = [] }

    comments.each do |comment|
      comments_by_parent[comment.parent_comment_id] << comment
    end

    comments_by_parent
  end

# Google Static Page API
  def static_page
    url = Addressable::URI.new(
        :scheme => "https",
        :host => "maps.googleapis.com",
        :path => "/maps/api/staticmap",
        :query_values => {
          :center => "#{self.latitude},#{self.longitude}",
          :zoom => 17,
          :markers => "markerStyles|#{self.latitude},#{self.longitude}|",
          :size => "500x400",
          :sensor => "false"
        }).to_s
  end
# Google Directions API  
  def get_directions(lat_origin, long_origin)
    url = Addressable::URI.new(
        :scheme => "https",
        :host => "maps.googleapis.com",
        :path => "/maps/api/directions/json",
        :query_values => {
          :origin => "#{lat_origin},#{long_origin}",
          :destination => "#{self.latitude},#{self.longitude}",
          :sensor => "false",
          :mode => "walking"
        }).to_s
    url
    response = JSON.parse(RestClient.get(url))
    if response["routes"] != []
      instructions = response["routes"][0]["legs"][0]["steps"].map do |step|
        html = step["html_instructions"].gsub("Destination", ". Destination")
        Nokogiri::HTML(html).text + "."
      end
      return instructions
    else
      return nil
    end
  end
  
  def as_json(options)
    comments = (self.comments != []) ? self.comments : {} 
    comments_by_parent_id = (self.comments_by_parent_id != []) ? self.comments_by_parent_id : {}
    uservotes = (self.uservotes != []) ? self.uservotes : {}
    favorites = (self.favorites != []) ? self.favorites : {}
    
    additional_options = {image_url: self.image.url}
    additional_options.merge!({comments: comments}) 
    additional_options.merge!({comments_by_parent_id: comments_by_parent_id}) 
    additional_options.merge!({uservotes: uservotes}) 
    additional_options.merge!({favorites: favorites}) 
    
    super(options).merge!(additional_options)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :logged_in?

  respond_to :json
  
  def index
    @photos = Photo.order(:id).includes(:comments).reverse
    
    respond json: @photos
  end
  
  def create  
    tempfile = params[:photo][:image].tempfile
    params[:photo][:submitter_id] = params[:user_id]
    
    @photo = Photo.new(params[:photo])
    @photo.check_for_geotag(tempfile)
    
    if @photo.save
      respond_with @photo
    else
      flash[:errors] = @photo.errors.full_messages
      respond_with @photo
    end
  end

  def show
    @photo = Photo.find(params[:id])
    respond_with @photo
  end

  def update
    @photo = Photo.find(params[:id])
    @photo.update_attributes(params[:photo])
    render json: @photo
  end
  
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    respond_with @photo
  end

  def upvote
    @uservote = UserVote.find_by_user_id_and_photo_id(self.current_user.id, params[:id])
    if @uservote
      @uservote.update_attributes(value: 1)
    else
      UserVote.create(value: 1, user_id: self.current_user.id, photo_id: params[:id])
    end
    respond_with Photo.find(params[:id])
  end

  def downvote
    @uservote = UserVote.find_by_user_id_and_photo_id(self.current_user.id, params[:id])
    if @uservote
      @uservote.update_attributes(value: -1)
    else
      UserVote.create(value: -1, user_id: self.current_user.id, photo_id: params[:id])
    end
    respond_with Photo.find(params[:id])
  end
  
  def cancelvote
    @uservote = UserVote.find_by_user_id_and_photo_id(self.current_user.id, params[:id])
    if @uservote
      @uservote.update_attributes(value: 0)
    else
      UserVote.create(value: 0, user_id: self.current_user.id, photo_id: params[:id])
    end
    respond_with Photo.find(params[:id])
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_comment.html.erb
<p>
  User: <%= User.find(top_level_comment.commenter_id).username %>
  <br>
  <%= top_level_comment.body %>
  <%= link_to "Reply", new_photo_comment_url(photo.id, {parent_comment_id: top_level_comment.id}) %>
</p>

<ul>
  <% comments_by_parent[top_level_comment.id].each do |child_comment| %>
    <li><%= render "comment", photo: @photo, top_level_comment: child_comment, comments_by_parent: comments_by_parent %></li>
  <% end %>
</ul>

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>

<form action="<%= photo_url(@photo.id) %>" action="post">
	<input type="hidden"
		   name="_method"
		  value="put">
	
	<label>Title
	    <input type="text" name="photo[title]" value="<%= @photo.title %>">
	</label>
	
	<label>Description
	    <input type="text" name="photo[title]" value="<%= @photo.description %>">
	</label>
	
	<input type="submit" value="Edit Photo">
	
</form>

<%= button_to "Delete Photo", photo_url(@photo.id), method: :delete %>

app/views/photos/new.html.erb
<h1>Upload a Photo!</h1>

<%= form_for @photo, url: user_photos_url do |f| %>

  <%= f.label :Title %>:
  <%= f.text_field :title %><br />

  <%= f.label :Description %>:
  <%= f.text_field :description %><br />

  <%= f.label :Latitude %>:
  <%= f.text_field :latitude %><br />

  <%= f.label :Longitude %>:
  <%= f.text_field :longitude %><br />

  <%= f.file_field :image %><br />

  <%= f.submit %>

<% end %>

app/views/photos/show.html.erb
<section class="photo_show">

  <section class="photo_object">
    <h1><%= @photo.title %></h1>

    <div class="image_show" >
      <%= image_tag @photo.image.url %>
    </div>

    <p>Description: <%= @photo.description %></p>

    <div class="image_show_votes">
      <%= button_to "Upvote", upvote_photo_url, method: :post, class: "vote_button" %>
      <%= button_to "Downvote", downvote_photo_url, method: :post, class: "vote_button" %>
      <p>Vote Count: <%= @photo.uservotes.sum("value") %></p>
    </div>

    <div class="comments">
      <%= link_to "Post a new comment", new_photo_comment_url(@photo.id) %>
      <h4>Comments:</h4>
      <ul>
        <% comments_by_parent = @photo.comments_by_parent_id %>
        <% comments_by_parent[nil].each do |top_level_comment| %>
          <li>
            <%= render "comment", photo: @photo, top_level_comment: top_level_comment, comments_by_parent: comments_by_parent %>
          </li>
        <% end %>
      </ul>
    </div>

  </section>

  <div class="browse_buttons">
    <% if !Photo.find(:first, conditions:["id < ?", @photo.id]).nil? %>
      <a href="<%= photo_url(Photo.find(:first, conditions:["id < ?", @photo.id]).id) %>"><p>Prev</p></a>
    <% end %>

    <% if !Photo.find(:first, conditions:["id > ?", @photo.id]).nil? %>
      <a href="<%= photo_url(Photo.find(:first, conditions:["id > ?", @photo.id]).id) %>"><p>Next</p></a>
    <% end %>
  </div>

  <div class="favorite_buttons">
    <% favorite = @photo.favorites.where(user_id: self.current_user.id) %>
    <% if favorite && !favorite.empty? %>
      <%= button_to "Unfavorite", favorite_url(favorite.first.id), method: :delete %>
    <% else %>
      <%= button_to "Favorite", photo_favorites_url(@photo.id), method: :post %>
    <% end %>
  </div>

  <div class="standard_map">
    <img src="<%= @photo.static_page %>">
  </div>
	
	<div class="directions">
		<% direction_steps = @photo.get_directions(self.current_user.latitude, self.current_user.longitude) %>
		<% unless direction_steps.nil? %>
			<%= render "shared/directions", directions: direction_steps %>
		<% end %>
	</div>

</section>